### ISSUE TITLE
Installation no longer possible

### ISSUE THREAD

**Issue by KristjanESPERANTO** [balassy/MMM-ModuleToggleButton#5]
Since `grunt-stylelint` is not compatible with `stylelint` v16, the module can no longer be installed without further ado ([see corresponding entry in the forum](https://forum.magicmirror.builders/topic/18509/mmm-moduletogglebutton-suddenly-broken)).

**Comment by balassy** [comment]
Thank you for reporting this issue.

Actually `stylelint` is not necessary for this module since it does not render anything to the user interface and does not contain any CSS file. Now I have updated all dependencies to the latest version, and removed both grunt and stylelint.

See commit https://github.com/balassy/MMM-ModuleToggleButton/commit/3292361a958628eb213b46d7aacb243546d0db83 and PR https://github.com/balassy/MMM-ModuleToggleButton/pull/6.

Please use the latest 1.0.1 version.

Thanks again.
